/**
 * Product Model
 * Defines the schema for e-commerce products
 */

const productSchema = {
	id: {
		type: 'auto-increment',
		required: true,
		unique: true
	},
	name: {
		type: String,
		required: true,
		minlength: 3,
		maxlength: 100
	},
	description: {
		type: String,
		required: false,
		maxlength: 500
	},
	price: {
		type: Number,
		required: true,
		min: 0.01
	},
	originalPrice: {
		type: Number,
		required: false,
		min: 0.01
	},
	category: {
		type: String,
		enum: ['electronics', 'devices', 'foodstuffs', 'accessories', 'home', 'personal-care', 'beauty', 'books', 'clothing'],
		required: true
	},
	subcategory: {
		type: String,
		required: false
	},
	stock: {
		type: Number,
		required: true,
		default: 0,
		min: 0
	},
	image: {
		type: String,
		required: true,
		default: '📦'
	},
	rating: {
		type: Number,
		required: false,
		min: 0,
		max: 5,
		default: 0
	},
	reviews: {
		type: Number,
		required: false,
		default: 0,
		min: 0
	},
	sku: {
		type: String,
		required: true,
		unique: true
	},
	inStock: {
		type: Boolean,
		default: function() {
			return this.stock > 0;
		}
	},
	featured: {
		type: Boolean,
		default: false
	},
	createdAt: {
		type: Date,
		default: Date.now
	},
	updatedAt: {
		type: Date,
		default: Date.now
	}
};

// Mock database with initial products
const mockProducts = [
	// ========================================
	// ELECTRONICS
	// ========================================
	{
		id: 1,
		name: 'Wireless Headphones Pro',
		description: 'High-quality wireless headphones with noise cancellation',
		price: 79.99,
		originalPrice: 129.99,
		category: 'electronics',
		subcategory: 'audio',
		stock: 45,
		image: '🎧',
		rating: 4.5,
		reviews: 128,
		sku: 'HDPH-001',
		inStock: true,
		featured: true
	},
	{
		id: 2,
		name: 'Smart Watch Ultra',
		description: 'Advanced smartwatch with fitness tracking',
		price: 199.99,
		originalPrice: 299.99,
		category: 'electronics',
		subcategory: 'wearables',
		stock: 28,
		image: '⌚',
		rating: 4.8,
		reviews: 256,
		sku: 'SMWT-001',
		inStock: true,
		featured: true
	},
	{
		id: 6,
		name: 'Portable Charger 20000mAh',
		description: 'Fast-charging portable power bank',
		price: 34.99,
		originalPrice: 59.99,
		category: 'electronics',
		subcategory: 'power',
		stock: 56,
		image: '🔋',
		rating: 4.7,
		reviews: 178,
		sku: 'PBVK-001',
		inStock: true,
		featured: true
	},
	{
		id: 7,
		name: 'Mechanical Keyboard RGB',
		description: 'Gaming keyboard with RGB lighting and mechanical switches',
		price: 129.99,
		originalPrice: 199.99,
		category: 'electronics',
		subcategory: 'peripherals',
		stock: 34,
		image: '⌨️',
		rating: 4.9,
		reviews: 467,
		sku: 'KBRD-001',
		inStock: true,
		featured: true
	},
	{
		id: 9,
		name: 'Monitor 4K Display',
		description: '27-inch 4K ultra HD monitor with HDR support',
		price: 349.99,
		originalPrice: 499.99,
		category: 'electronics',
		subcategory: 'displays',
		stock: 15,
		image: '🖨️',
		rating: 4.7,
		reviews: 98,
		sku: 'MNTR-001',
		inStock: true,
		featured: true
	},
	{
		id: 24,
		name: 'Bluetooth Speaker Pro',
		description: '360-degree sound wireless Bluetooth speaker',
		price: 59.99,
		originalPrice: 99.99,
		category: 'electronics',
		subcategory: 'audio',
		stock: 40,
		image: '🔊',
		rating: 4.6,
		reviews: 203,
		sku: 'BLSP-001',
		inStock: true,
		featured: false
	},

	// ========================================
	// DEVICES (Phones, Tablets, etc.)
	// ========================================
	{
		id: 11,
		name: 'Smartphone Pro Max',
		description: '6.7-inch OLED display with 5G and 256GB storage',
		price: 899.99,
		originalPrice: 1099.99,
		category: 'devices',
		subcategory: 'smartphones',
		stock: 12,
		image: '📱',
		rating: 4.8,
		reviews: 589,
		sku: 'SMPH-001',
		inStock: true,
		featured: true
	},
	{
		id: 12,
		name: 'Tablet Ultra 12-inch',
		description: 'Lightweight tablet with M2 processor and stylus support',
		price: 599.99,
		originalPrice: 799.99,
		category: 'devices',
		subcategory: 'tablets',
		stock: 20,
		image: '📲',
		rating: 4.7,
		reviews: 342,
		sku: 'TBLT-001',
		inStock: true,
		featured: true
	},
	{
		id: 13,
		name: 'Laptop Gaming 15-inch',
		description: 'RTX 4070 GPU with Intel i9 processor and 32GB RAM',
		price: 1299.99,
		originalPrice: 1699.99,
		category: 'devices',
		subcategory: 'laptops',
		stock: 8,
		image: '💻',
		rating: 4.9,
		reviews: 267,
		sku: 'LPTOP-001',
		inStock: true,
		featured: true
	},
	{
		id: 14,
		name: 'Wireless Earbuds Pro',
		description: 'Noise-canceling earbuds with 8-hour battery life',
		price: 159.99,
		originalPrice: 229.99,
		category: 'devices',
		subcategory: 'audio',
		stock: 50,
		image: '🎵',
		rating: 4.6,
		reviews: 421,
		sku: 'EBRDS-001',
		inStock: true,
		featured: false
	},
	{
		id: 15,
		name: 'Desktop Computer High-Performance',
		description: 'Workstation with RTX 4090, Ryzen 9, and 64GB RAM',
		price: 2499.99,
		originalPrice: 3199.99,
		category: 'devices',
		subcategory: 'computers',
		stock: 5,
		image: '🖥️',
		rating: 4.8,
		reviews: 156,
		sku: 'DSKTP-001',
		inStock: true,
		featured: true
	},

	// ========================================
	// FOODSTUFFS & GROCERIES
	// ========================================
	{
		id: 16,
		name: 'Organic Almond Butter',
		description: '12 oz jar of 100% pure organic almond butter',
		price: 8.99,
		originalPrice: 12.99,
		category: 'foodstuffs',
		subcategory: 'spreads',
		stock: 120,
		image: '🥜',
		rating: 4.7,
		reviews: 234,
		sku: 'FOOD-001',
		inStock: true,
		featured: false
	},
	{
		id: 17,
		name: 'Whole Wheat Bread',
		description: 'Fresh whole grain bread loaf',
		price: 3.49,
		originalPrice: 4.99,
		category: 'foodstuffs',
		subcategory: 'bakery',
		stock: 80,
		image: '🍞',
		rating: 4.5,
		reviews: 145,
		sku: 'FOOD-002',
		inStock: true,
		featured: false
	},
	{
		id: 18,
		name: 'Mixed Vegetables Frozen',
		description: '2 lb bag of frozen broccoli, carrots, and peppers',
		price: 4.99,
		originalPrice: 6.99,
		category: 'foodstuffs',
		subcategory: 'frozen',
		stock: 150,
		image: '🥦',
		rating: 4.6,
		reviews: 189,
		sku: 'FOOD-003',
		inStock: true,
		featured: false
	},
	{
		id: 19,
		name: 'Organic Milk 1 Gallon',
		description: 'Fresh organic whole milk',
		price: 5.49,
		originalPrice: 7.99,
		category: 'foodstuffs',
		subcategory: 'dairy',
		stock: 200,
		image: '🥛',
		rating: 4.8,
		reviews: 512,
		sku: 'FOOD-004',
		inStock: true,
		featured: false
	},
	{
		id: 20,
		name: 'Greek Yogurt Plain',
		description: '32 oz container of creamy Greek yogurt',
		price: 4.29,
		originalPrice: 5.99,
		category: 'foodstuffs',
		subcategory: 'dairy',
		stock: 100,
		image: '🥛',
		rating: 4.7,
		reviews: 267,
		sku: 'FOOD-005',
		inStock: true,
		featured: false
	},
	{
		id: 21,
		name: 'Brown Rice 5 lb',
		description: 'Long-grain brown rice for healthy meals',
		price: 6.99,
		originalPrice: 9.99,
		category: 'foodstuffs',
		subcategory: 'grains',
		stock: 75,
		image: '🍚',
		rating: 4.6,
		reviews: 134,
		sku: 'FOOD-006',
		inStock: true,
		featured: false
	},
	{
		id: 22,
		name: 'Salmon Fillets Frozen',
		description: '1 lb fresh frozen Atlantic salmon fillets',
		price: 12.99,
		originalPrice: 17.99,
		category: 'foodstuffs',
		subcategory: 'seafood',
		stock: 45,
		image: '🐟',
		rating: 4.8,
		reviews: 198,
		sku: 'FOOD-007',
		inStock: true,
		featured: true
	},
	{
		id: 23,
		name: 'Chicken Breast Organic',
		description: '2 lbs of organic free-range chicken breast',
		price: 9.99,
		originalPrice: 14.99,
		category: 'foodstuffs',
		subcategory: 'meat',
		stock: 60,
		image: '🍗',
		rating: 4.7,
		reviews: 321,
		sku: 'FOOD-008',
		inStock: true,
		featured: false
	},
	{
		id: 25,
		name: 'Honey Raw 16 oz',
		description: 'Pure raw unfiltered honey',
		price: 7.99,
		originalPrice: 11.99,
		category: 'foodstuffs',
		subcategory: 'condiments',
		stock: 85,
		image: '🍯',
		rating: 4.9,
		reviews: 276,
		sku: 'FOOD-009',
		inStock: true,
		featured: false
	},
	{
		id: 26,
		name: 'Almond Milk 1 Gallon',
		description: 'Unsweetened organic almond milk',
		price: 3.99,
		originalPrice: 5.49,
		category: 'foodstuffs',
		subcategory: 'beverages',
		stock: 110,
		image: '🥛',
		rating: 4.5,
		reviews: 203,
		sku: 'FOOD-010',
		inStock: true,
		featured: false
	},

	// ========================================
	// ACCESSORIES
	// ========================================
	{
		id: 3,
		name: 'Laptop Stand Aluminum',
		description: 'Premium aluminum laptop stand for better ergonomics',
		price: 49.99,
		originalPrice: 79.99,
		category: 'accessories',
		subcategory: 'desk',
		stock: 62,
		image: '🖥️',
		rating: 4.6,
		reviews: 89,
		sku: 'LPST-001',
		inStock: true,
		featured: false
	},
	{
		id: 4,
		name: 'USB-C Cable (2m)',
		description: 'Durable USB-C charging and data transfer cable',
		price: 12.99,
		originalPrice: 19.99,
		category: 'accessories',
		subcategory: 'cables',
		stock: 150,
		image: '🔌',
		rating: 4.3,
		reviews: 342,
		sku: 'USBC-001',
		inStock: true,
		featured: false
	},
	{
		id: 5,
		name: 'Phone Case Protective',
		description: 'Protective phone case with anti-slip grip',
		price: 24.99,
		originalPrice: 39.99,
		category: 'accessories',
		subcategory: 'protection',
		stock: 89,
		image: '📱',
		rating: 4.4,
		reviews: 215,
		sku: 'PHCS-001',
		inStock: true,
		featured: false
	},
	{
		id: 8,
		name: 'Mouse Pad Extended',
		description: 'Large extended mouse pad for gaming',
		price: 19.99,
		originalPrice: 29.99,
		category: 'accessories',
		subcategory: 'peripherals',
		stock: 98,
		image: '🖱️',
		rating: 4.5,
		reviews: 145,
		sku: 'MSPD-001',
		inStock: true,
		featured: false
	},
	{
		id: 10,
		name: 'Camera 4K Action',
		description: 'Compact 4K action camera for adventures',
		price: 89.99,
		originalPrice: 149.99,
		category: 'accessories',
		subcategory: 'cameras',
		stock: 22,
		image: '📷',
		rating: 4.6,
		reviews: 134,
		sku: 'ACAM-001',
		inStock: true,
		featured: false
	},

	// ========================================
	// HOME & KITCHEN
	// ========================================
	{
		id: 27,
		name: 'Non-Stick Cookware Set',
		description: '12-piece non-stick kitchen cookware set',
		price: 79.99,
		originalPrice: 129.99,
		category: 'home',
		subcategory: 'kitchen',
		stock: 35,
		image: '🍳',
		rating: 4.7,
		reviews: 189,
		sku: 'HOME-001',
		inStock: true,
		featured: false
	},
	{
		id: 28,
		name: 'Stainless Steel Water Bottle',
		description: '40 oz insulated water bottle keeps drinks cold for 24 hours',
		price: 24.99,
		originalPrice: 39.99,
		category: 'home',
		subcategory: 'drinkware',
		stock: 110,
		image: '🧊',
		rating: 4.8,
		reviews: 412,
		sku: 'HOME-002',
		inStock: true,
		featured: false
	},
	{
		id: 29,
		name: 'Microfiber Kitchen Towels',
		description: 'Set of 6 ultra-absorbent microfiber towels',
		price: 14.99,
		originalPrice: 22.99,
		category: 'home',
		subcategory: 'textiles',
		stock: 85,
		image: '🧽',
		rating: 4.6,
		reviews: 267,
		sku: 'HOME-003',
		inStock: true,
		featured: false
	},

	// ========================================
	// PERSONAL CARE
	// ========================================
	{
		id: 30,
		name: 'Organic Shampoo 500ml',
		description: 'Sulfate-free organic shampoo for all hair types',
		price: 8.99,
		originalPrice: 12.99,
		category: 'personal-care',
		subcategory: 'hair',
		stock: 95,
		image: '🧴',
		rating: 4.5,
		reviews: 156,
		sku: 'PC-001',
		inStock: true,
		featured: false
	},
	{
		id: 31,
		name: 'Natural Deodorant Stick',
		description: 'Aluminum-free natural deodorant',
		price: 6.99,
		originalPrice: 9.99,
		category: 'personal-care',
		subcategory: 'body',
		stock: 120,
		image: '💪',
		rating: 4.4,
		reviews: 203,
		sku: 'PC-002',
		inStock: true,
		featured: false
	},
	{
		id: 32,
		name: 'Organic Face Moisturizer',
		description: '50ml hypoallergenic face moisturizer',
		price: 15.99,
		originalPrice: 24.99,
		category: 'personal-care',
		subcategory: 'skincare',
		stock: 65,
		image: '🧴',
		rating: 4.7,
		reviews: 289,
		sku: 'PC-003',
		inStock: true,
		featured: false
	},

	// ========================================
	// BEAUTY
	// ========================================
	{
		id: 33,
		name: 'Lipstick Professional Set',
		description: 'Set of 12 long-lasting lipsticks in various shades',
		price: 19.99,
		originalPrice: 34.99,
		category: 'beauty',
		subcategory: 'makeup',
		stock: 50,
		image: '💄',
		rating: 4.6,
		reviews: 178,
		sku: 'BEAUT-001',
		inStock: true,
		featured: false
	},
	{
		id: 34,
		name: 'Makeup Brush Set Premium',
		description: '18-piece professional makeup brush set with case',
		price: 29.99,
		originalPrice: 49.99,
		category: 'beauty',
		subcategory: 'tools',
		stock: 45,
		image: '🎨',
		rating: 4.8,
		reviews: 234,
		sku: 'BEAUT-002',
		inStock: true,
		featured: false
	},
	{
		id: 35,
		name: 'Mascara Waterproof Volume',
		description: 'Professional volume mascara that lasts all day',
		price: 11.99,
		originalPrice: 17.99,
		category: 'beauty',
		subcategory: 'makeup',
		stock: 75,
		image: '👁️',
		rating: 4.7,
		reviews: 201,
		sku: 'BEAUT-003',
		inStock: true,
		featured: false
	},

	// ========================================
	// ADDITIONAL ELECTRONICS
	// ========================================
	{
		id: 36,
		name: 'Wireless Mouse Ergonomic',
		description: 'Ergonomic wireless mouse with USB receiver',
		price: 34.99,
		originalPrice: 49.99,
		category: 'electronics',
		subcategory: 'peripherals',
		stock: 68,
		image: '🖱️',
		rating: 4.5,
		reviews: 156,
		sku: 'ELEC-001',
		inStock: true,
		featured: false
	},
	{
		id: 37,
		name: 'USB Hub 7-Port',
		description: 'Multi-port USB hub with fast data transfer',
		price: 29.99,
		originalPrice: 44.99,
		category: 'electronics',
		subcategory: 'peripherals',
		stock: 80,
		image: '🔌',
		rating: 4.4,
		reviews: 89,
		sku: 'ELEC-002',
		inStock: true,
		featured: false
	},
	{
		id: 38,
		name: 'Webcam 1080P HD',
		description: 'Crystal clear 1080p webcam with microphone',
		price: 54.99,
		originalPrice: 79.99,
		category: 'electronics',
		subcategory: 'cameras',
		stock: 42,
		image: '📹',
		rating: 4.6,
		reviews: 178,
		sku: 'ELEC-003',
		inStock: true,
		featured: false
	},

	// ========================================
	// ADDITIONAL DEVICES
	// ========================================
	{
		id: 39,
		name: 'Smartwatch Fitness Band',
		description: 'Water-resistant fitness tracker with heart rate monitor',
		price: 79.99,
		originalPrice: 119.99,
		category: 'devices',
		subcategory: 'wearables',
		stock: 55,
		image: '⌚',
		rating: 4.5,
		reviews: 267,
		sku: 'DEV-001',
		inStock: true,
		featured: false
	},
	{
		id: 40,
		name: 'Portable SSD 1TB',
		description: 'Ultra-fast 1TB portable solid state drive',
		price: 129.99,
		originalPrice: 179.99,
		category: 'devices',
		subcategory: 'storage',
		stock: 33,
		image: '💾',
		rating: 4.8,
		reviews: 234,
		sku: 'DEV-002',
		inStock: true,
		featured: false
	},
	{
		id: 41,
		name: 'Mechanical Gaming Mouse',
		description: 'Gaming mouse with customizable RGB and DPI',
		price: 69.99,
		originalPrice: 99.99,
		category: 'devices',
		subcategory: 'peripherals',
		stock: 47,
		image: '🖱️',
		rating: 4.7,
		reviews: 312,
		sku: 'DEV-003',
		inStock: true,
		featured: true
	},

	// ========================================
	// ADDITIONAL FOODSTUFFS
	// ========================================
	{
		id: 42,
		name: 'Pasta Whole Wheat 1kg',
		description: 'Nutritious whole wheat pasta',
		price: 2.99,
		originalPrice: 4.49,
		category: 'foodstuffs',
		subcategory: 'pasta',
		stock: 200,
		image: '🍝',
		rating: 4.5,
		reviews: 145,
		sku: 'FOOD-011',
		inStock: true,
		featured: false
	},
	{
		id: 43,
		name: 'Olive Oil Extra Virgin 500ml',
		description: 'Premium extra virgin olive oil',
		price: 13.99,
		originalPrice: 19.99,
		category: 'foodstuffs',
		subcategory: 'oils',
		stock: 60,
		image: '🫒',
		rating: 4.8,
		reviews: 289,
		sku: 'FOOD-012',
		inStock: true,
		featured: false
	},
	{
		id: 44,
		name: 'Coffee Beans Premium 1lb',
		description: 'Freshly roasted premium coffee beans',
		price: 11.99,
		originalPrice: 16.99,
		category: 'foodstuffs',
		subcategory: 'beverages',
		stock: 78,
		image: '☕',
		rating: 4.9,
		reviews: 401,
		sku: 'FOOD-013',
		inStock: true,
		featured: true
	},
	{
		id: 45,
		name: 'Cheddar Cheese Block 1lb',
		description: 'Aged sharp cheddar cheese',
		price: 6.99,
		originalPrice: 9.99,
		category: 'foodstuffs',
		subcategory: 'dairy',
		stock: 95,
		image: '🧀',
		rating: 4.6,
		reviews: 156,
		sku: 'FOOD-014',
		inStock: true,
		featured: false
	},
	{
		id: 46,
		name: 'Mixed Nuts & Seeds',
		description: '16 oz bag of roasted mixed nuts and seeds',
		price: 7.99,
		originalPrice: 11.99,
		category: 'foodstuffs',
		subcategory: 'snacks',
		stock: 110,
		image: '🥜',
		rating: 4.7,
		reviews: 203,
		sku: 'FOOD-015',
		inStock: true,
		featured: false
	},
	{
		id: 47,
		name: 'Green Tea Bags 25 Pack',
		description: 'Premium organic green tea bags',
		price: 5.99,
		originalPrice: 8.99,
		category: 'foodstuffs',
		subcategory: 'beverages',
		stock: 140,
		image: '🍵',
		rating: 4.5,
		reviews: 178,
		sku: 'FOOD-016',
		inStock: true,
		featured: false
	},

	// ========================================
	// ADDITIONAL ACCESSORIES
	// ========================================
	{
		id: 48,
		name: 'HDMI Cable 2.1 4K',
		description: 'Ultra High-Speed HDMI 2.1 cable for 4K/8K',
		price: 19.99,
		originalPrice: 29.99,
		category: 'accessories',
		subcategory: 'cables',
		stock: 120,
		image: '🔌',
		rating: 4.4,
		reviews: 98,
		sku: 'ACC-001',
		inStock: true,
		featured: false
	},
	{
		id: 49,
		name: 'Screen Protector Tempered Glass',
		description: 'Tempered glass screen protector for smartphones',
		price: 8.99,
		originalPrice: 12.99,
		category: 'accessories',
		subcategory: 'protection',
		stock: 180,
		image: '📱',
		rating: 4.6,
		reviews: 312,
		sku: 'ACC-002',
		inStock: true,
		featured: false
	},
	{
		id: 50,
		name: 'Laptop Cooling Pad',
		description: 'Active cooling pad with dual fans for laptops',
		price: 44.99,
		originalPrice: 64.99,
		category: 'accessories',
		subcategory: 'cooling',
		stock: 38,
		image: '❄️',
		rating: 4.7,
		reviews: 145,
		sku: 'ACC-003',
		inStock: true,
		featured: false
	},
	{
		id: 51,
		name: 'Power Bank 10000mAh',
		description: 'Compact 10000mAh power bank with fast charging',
		price: 24.99,
		originalPrice: 36.99,
		category: 'accessories',
		subcategory: 'power',
		stock: 95,
		image: '🔋',
		rating: 4.5,
		reviews: 267,
		sku: 'ACC-004',
		inStock: true,
		featured: false
	},

	// ========================================
	// ADDITIONAL HOME & KITCHEN
	// ========================================
	{
		id: 52,
		name: 'Stainless Steel Knife Set',
		description: '5-piece professional chef knife set',
		price: 49.99,
		originalPrice: 79.99,
		category: 'home',
		subcategory: 'kitchen',
		stock: 28,
		image: '🔪',
		rating: 4.8,
		reviews: 189,
		sku: 'HOME-004',
		inStock: true,
		featured: false
	},
	{
		id: 53,
		name: 'Coffee Maker Programmable',
		description: '12-cup programmable coffee maker with timer',
		price: 59.99,
		originalPrice: 89.99,
		category: 'home',
		subcategory: 'appliances',
		stock: 22,
		image: '☕',
		rating: 4.6,
		reviews: 134,
		sku: 'HOME-005',
		inStock: true,
		featured: false
	},
	{
		id: 54,
		name: 'Food Storage Container Set',
		description: 'Set of 8 airtight glass food containers',
		price: 34.99,
		originalPrice: 49.99,
		category: 'home',
		subcategory: 'storage',
		stock: 67,
		image: '📦',
		rating: 4.7,
		reviews: 201,
		sku: 'HOME-006',
		inStock: true,
		featured: false
	},
	{
		id: 55,
		name: 'Bamboo Cutting Board Set',
		description: 'Set of 3 natural bamboo cutting boards',
		price: 24.99,
		originalPrice: 39.99,
		category: 'home',
		subcategory: 'kitchen',
		stock: 45,
		image: '🪵',
		rating: 4.5,
		reviews: 123,
		sku: 'HOME-007',
		inStock: true,
		featured: false
	},

	// ========================================
	// ADDITIONAL PERSONAL CARE
	// ========================================
	{
		id: 56,
		name: 'Toothpaste Whitening 100ml',
		description: 'Natural whitening toothpaste',
		price: 5.99,
		originalPrice: 8.99,
		category: 'personal-care',
		subcategory: 'dental',
		stock: 150,
		image: '🦷',
		rating: 4.4,
		reviews: 212,
		sku: 'PC-004',
		inStock: true,
		featured: false
	},
	{
		id: 57,
		name: 'Body Lotion Moisturizing',
		description: '250ml nourishing body lotion',
		price: 7.99,
		originalPrice: 11.99,
		category: 'personal-care',
		subcategory: 'body',
		stock: 108,
		image: '🧴',
		rating: 4.6,
		reviews: 189,
		sku: 'PC-005',
		inStock: true,
		featured: false
	},
	{
		id: 58,
		name: 'Hair Conditioner 500ml',
		description: 'Deep conditioning hair treatment',
		price: 9.99,
		originalPrice: 14.99,
		category: 'personal-care',
		subcategory: 'hair',
		stock: 85,
		image: '🧴',
		rating: 4.7,
		reviews: 267,
		sku: 'PC-006',
		inStock: true,
		featured: false
	},

	// ========================================
	// ADDITIONAL BEAUTY
	// ========================================
	{
		id: 59,
		name: 'Foundation Liquid 30ml',
		description: 'Full coverage liquid foundation',
		price: 14.99,
		originalPrice: 22.99,
		category: 'beauty',
		subcategory: 'makeup',
		stock: 62,
		image: '💄',
		rating: 4.6,
		reviews: 234,
		sku: 'BEAUT-004',
		inStock: true,
		featured: false
	},
	{
		id: 60,
		name: 'Eyeshadow Palette 12-Color',
		description: 'Professional 12-color eyeshadow palette',
		price: 16.99,
		originalPrice: 26.99,
		category: 'beauty',
		subcategory: 'makeup',
		stock: 48,
		image: '👁️',
		rating: 4.8,
		reviews: 298,
		sku: 'BEAUT-005',
		inStock: true,
		featured: true
	},
	{
		id: 61,
		name: 'Perfume Eau de Toilette 100ml',
		description: 'Luxurious fragrance with lasting scent',
		price: 39.99,
		originalPrice: 59.99,
		category: 'beauty',
		subcategory: 'fragrance',
		stock: 35,
		image: '💐',
		rating: 4.7,
		reviews: 156,
		sku: 'BEAUT-006',
		inStock: true,
		featured: true
	},

	// ========================================
	// CLOTHING
	// ========================================
	{
		id: 62,
		name: 'Cotton T-Shirt Classic',
		description: '100% organic cotton classic t-shirt',
		price: 14.99,
		originalPrice: 24.99,
		category: 'clothing',
		subcategory: 'tops',
		stock: 120,
		image: '👕',
		rating: 4.5,
		reviews: 289,
		sku: 'CLTH-001',
		inStock: true,
		featured: false
	},
	{
		id: 63,
		name: 'Jeans Slim Fit',
		description: 'Comfortable slim fit denim jeans',
		price: 49.99,
		originalPrice: 79.99,
		category: 'clothing',
		subcategory: 'bottoms',
		stock: 67,
		image: '👖',
		rating: 4.6,
		reviews: 201,
		sku: 'CLTH-002',
		inStock: true,
		featured: false
	},
	{
		id: 64,
		name: 'Hoodie Fleece Warm',
		description: 'Soft fleece hoodie for comfort',
		price: 39.99,
		originalPrice: 64.99,
		category: 'clothing',
		subcategory: 'outerwear',
		stock: 54,
		image: '🧥',
		rating: 4.7,
		reviews: 178,
		sku: 'CLTH-003',
		inStock: true,
		featured: false
	},
	{
		id: 65,
		name: 'Sneakers Athletic Running',
		description: 'High-performance athletic running shoes',
		price: 79.99,
		originalPrice: 119.99,
		category: 'clothing',
		subcategory: 'footwear',
		stock: 43,
		image: '👟',
		rating: 4.8,
		reviews: 267,
		sku: 'CLTH-004',
		inStock: true,
		featured: true
	},
	{
		id: 66,
		name: 'Winter Coat Insulated',
		description: 'Warm insulated winter coat',
		price: 129.99,
		originalPrice: 189.99,
		category: 'clothing',
		subcategory: 'outerwear',
		stock: 28,
		image: '🧥',
		rating: 4.7,
		reviews: 145,
		sku: 'CLTH-005',
		inStock: true,
		featured: false
	},

	// ========================================
	// BOOKS
	// ========================================
	{
		id: 67,
		name: 'Fiction Novel: The Epic Advantage',
		description: 'Epic adventure novel, 500 pages',
		price: 15.99,
		originalPrice: 22.99,
		category: 'books',
		subcategory: 'fiction',
		stock: 75,
		image: '📖',
		rating: 4.6,
		reviews: 234,
		sku: 'BOOK-001',
		inStock: true,
		featured: false
	},
	{
		id: 68,
		name: 'Non-Fiction: Do The Imposible',
		description: 'Comprehensive guide to personal success',
		price: 19.99,
		originalPrice: 29.99,
		category: 'books',
		subcategory: 'non-fiction',
		stock: 52,
		image: '📚',
		rating: 4.8,
		reviews: 289,
		sku: 'BOOK-002',
		inStock: true,
		featured: true
	},
	{
		id: 69,
		name: 'Self-Help: Quiet Mind',
		description: 'Guide to mindfulness and meditation',
		price: 17.99,
		originalPrice: 25.99,
		category: 'books',
		subcategory: 'self-help',
		stock: 68,
		image: '🧘',
		rating: 4.7,
		reviews: 201,
		sku: 'BOOK-003',
		inStock: true,
		featured: false
	},
	{
		id: 70,
		name: 'Science: Quantum Physics',
		description: 'Introduction to quantum mechanics',
		price: 24.99,
		originalPrice: 34.99,
		category: 'books',
		subcategory: 'science',
		stock: 35,
		image: '⚛️',
		rating: 4.9,
		reviews: 156,
		sku: 'BOOK-004',
		inStock: true,
		featured: true
	},

	// ========================================
	// MORE ELECTRONICS
	// ========================================
	{
		id: 71,
		name: 'External Hard Drive 2TB',
		description: 'Portable 2TB external storage drive',
		price: 74.99,
		originalPrice: 109.99,
		category: 'electronics',
		subcategory: 'storage',
		stock: 41,
		image: '💾',
		rating: 4.6,
		reviews: 178,
		sku: 'ELEC-004',
		inStock: true,
		featured: false
	},
	{
		id: 72,
		name: 'Desk Lamp LED Smart',
		description: 'Smart LED desk lamp with adjustable color',
		price: 42.99,
		originalPrice: 64.99,
		category: 'electronics',
		subcategory: 'lighting',
		stock: 52,
		image: '💡',
		rating: 4.5,
		reviews: 145,
		sku: 'ELEC-005',
		inStock: true,
		featured: false
	},
	{
		id: 73,
		name: 'Surge Protector Power Strip',
		description: '6-outlet surge protector with 2 USB ports',
		price: 19.99,
		originalPrice: 29.99,
		category: 'electronics',
		subcategory: 'power',
		stock: 135,
		image: '🔌',
		rating: 4.4,
		reviews: 201,
		sku: 'ELEC-006',
		inStock: true,
		featured: false
	},

	// ========================================
	// MORE DEVICES
	// ========================================
	{
		id: 74,
		name: 'Bluetooth Headphones Over-Ear',
		description: 'Premium over-ear Bluetooth headphones',
		price: 99.99,
		originalPrice: 149.99,
		category: 'devices',
		subcategory: 'audio',
		stock: 38,
		image: '🎧',
		rating: 4.8,
		reviews: 345,
		sku: 'DEV-004',
		inStock: true,
		featured: true
	},
	{
		id: 75,
		name: 'USB-C Hub 11-in-1',
		description: 'All-in-one USB-C hub with multiple ports',
		price: 89.99,
		originalPrice: 129.99,
		category: 'devices',
		subcategory: 'adapters',
		stock: 29,
		image: '🔌',
		rating: 4.7,
		reviews: 187,
		sku: 'DEV-005',
		inStock: true,
		featured: false
	},
	{
		id: 76,
		name: 'Wireless Charging Pad',
		description: 'Fast 15W wireless charging pad for phones',
		price: 24.99,
		originalPrice: 39.99,
		category: 'devices',
		subcategory: 'charging',
		stock: 98,
		image: '🔋',
		rating: 4.5,
		reviews: 234,
		sku: 'DEV-006',
		inStock: true,
		featured: false
	},

	// ========================================
	// MORE FOODSTUFFS
	// ========================================
	{
		id: 77,
		name: 'Apple Granny Smith Fresh',
		description: '3 lb bag of fresh crisp apples',
		price: 4.49,
		originalPrice: 6.99,
		category: 'foodstuffs',
		subcategory: 'produce',
		stock: 180,
		image: '🍎',
		rating: 4.6,
		reviews: 112,
		sku: 'FOOD-017',
		inStock: true,
		featured: false
	},
	{
		id: 78,
		name: 'Banana Bunch Fresh',
		description: 'Fresh ripe bananas - 6 count',
		price: 1.99,
		originalPrice: 2.99,
		category: 'foodstuffs',
		subcategory: 'produce',
		stock: 250,
		image: '🍌',
		rating: 4.5,
		reviews: 156,
		sku: 'FOOD-018',
		inStock: true,
		featured: false
	},
	{
		id: 79,
		name: 'Broccoli Fresh Crown',
		description: 'Fresh organic broccoli crown',
		price: 2.99,
		originalPrice: 4.49,
		category: 'foodstuffs',
		subcategory: 'produce',
		stock: 145,
		image: '🥦',
		rating: 4.6,
		reviews: 89,
		sku: 'FOOD-019',
		inStock: true,
		featured: false
	},
	{
		id: 80,
		name: 'Orange Juice Fresh 64oz',
		description: 'Fresh pressed orange juice',
		price: 4.99,
		originalPrice: 7.49,
		category: 'foodstuffs',
		subcategory: 'beverages',
		stock: 125,
		image: '🧃',
		rating: 4.5,
		reviews: 178,
		sku: 'FOOD-020',
		inStock: true,
		featured: false
	},
	{
		id: 81,
		name: 'Chocolate Chips 12oz',
		description: 'Premium semi-sweet chocolate chips',
		price: 4.99,
		originalPrice: 7.99,
		category: 'foodstuffs',
		subcategory: 'baking',
		stock: 95,
		image: '🍫',
		rating: 4.8,
		reviews: 267,
		sku: 'FOOD-021',
		inStock: true,
		featured: false
	},
	{
		id: 82,
		name: 'Salmon Canned 5oz',
		description: 'Wild-caught canned salmon',
		price: 3.99,
		originalPrice: 5.99,
		category: 'foodstuffs',
		subcategory: 'canned',
		stock: 120,
		image: '🥫',
		rating: 4.4,
		reviews: 134,
		sku: 'FOOD-022',
		inStock: true,
		featured: false
	},
	{
		id: 83,
		name: 'Tomato Sauce 24oz',
		description: 'Organic tomato pasta sauce',
		price: 2.99,
		originalPrice: 4.49,
		category: 'foodstuffs',
		subcategory: 'sauces',
		stock: 160,
		image: '🍅',
		rating: 4.6,
		reviews: 201,
		sku: 'FOOD-023',
		inStock: true,
		featured: false
	},

	// ========================================
	// MORE ACCESSORIES
	// ========================================
	{
		id: 84,
		name: 'Phone Stand Adjustable',
		description: 'Adjustable phone stand for desk',
		price: 12.99,
		originalPrice: 19.99,
		category: 'accessories',
		subcategory: 'stands',
		stock: 168,
		image: '📱',
		rating: 4.5,
		reviews: 189,
		sku: 'ACC-005',
		inStock: true,
		featured: false
	},
	{
		id: 85,
		name: 'Wireless Charging Cable 1.5m',
		description: 'Braided wireless charging cable',
		price: 9.99,
		originalPrice: 14.99,
		category: 'accessories',
		subcategory: 'cables',
		stock: 145,
		image: '🔌',
		rating: 4.4,
		reviews: 156,
		sku: 'ACC-006',
		inStock: true,
		featured: false
	},
	{
		id: 86,
		name: 'Laptop Bag Canvas',
		description: 'Stylish canvas laptop carrying bag',
		price: 34.99,
		originalPrice: 54.99,
		category: 'accessories',
		subcategory: 'bags',
		stock: 58,
		image: '👜',
		rating: 4.6,
		reviews: 203,
		sku: 'ACC-007',
		inStock: true,
		featured: false
	},
	{
		id: 87,
		name: 'Screen Cleaner Kit',
		description: 'Complete screen cleaning kit with cloths',
		price: 8.99,
		originalPrice: 12.99,
		category: 'accessories',
		subcategory: 'cleaning',
		stock: 112,
		image: '🧹',
		rating: 4.5,
		reviews: 98,
		sku: 'ACC-008',
		inStock: true,
		featured: false
	},

	// ========================================
	// MORE HOME & KITCHEN
	// ========================================
	{
		id: 88,
		name: 'Blender High-Speed',
		description: '1000W high-speed blender',
		price: 84.99,
		originalPrice: 129.99,
		category: 'home',
		subcategory: 'appliances',
		stock: 19,
		image: '🥤',
		rating: 4.8,
		reviews: 267,
		sku: 'HOME-008',
		inStock: true,
		featured: true
	},
	{
		id: 89,
		name: 'Cookware Set Non-Stick 10pc',
		description: '10-piece non-stick cookware set',
		price: 99.99,
		originalPrice: 159.99,
		category: 'home',
		subcategory: 'kitchen',
		stock: 25,
		image: '🍳',
		rating: 4.7,
		reviews: 234,
		sku: 'HOME-009',
		inStock: true,
		featured: false
	},
	{
		id: 90,
		name: 'Vacuum Sealer Machine',
		description: 'Automatic vacuum food sealer',
		price: 44.99,
		originalPrice: 69.99,
		category: 'home',
		subcategory: 'storage',
		stock: 37,
		image: '🔒',
		rating: 4.6,
		reviews: 145,
		sku: 'HOME-010',
		inStock: true,
		featured: false
	},
	{
		id: 91,
		name: 'Dish Rack Stainless Steel',
		description: 'Compact stainless steel dish rack',
		price: 22.99,
		originalPrice: 35.99,
		category: 'home',
		subcategory: 'kitchen',
		stock: 89,
		image: '🍽️',
		rating: 4.5,
		reviews: 167,
		sku: 'HOME-011',
		inStock: true,
		featured: false
	},
	{
		id: 92,
		name: 'Tea Kettle Stainless Steel',
		description: 'Whistling stainless steel tea kettle',
		price: 19.99,
		originalPrice: 29.99,
		category: 'home',
		subcategory: 'kitchen',
		stock: 76,
		image: '☕',
		rating: 4.6,
		reviews: 201,
		sku: 'HOME-012',
		inStock: true,
		featured: false
	},

	// ========================================
	// MORE PERSONAL CARE
	// ========================================
	{
		id: 93,
		name: 'Face Wash Gentle Cleanser',
		description: '200ml gentle face cleansing wash',
		price: 8.99,
		originalPrice: 12.99,
		category: 'personal-care',
		subcategory: 'skincare',
		stock: 125,
		image: '🧴',
		rating: 4.6,
		reviews: 234,
		sku: 'PC-007',
		inStock: true,
		featured: false
	},
	{
		id: 94,
		name: 'Hand Soap Antibacterial',
		description: '500ml antibacterial hand soap',
		price: 3.99,
		originalPrice: 5.99,
		category: 'personal-care',
		subcategory: 'body',
		stock: 200,
		image: '🧼',
		rating: 4.5,
		reviews: 178,
		sku: 'PC-008',
		inStock: true,
		featured: false
	},
	{
		id: 95,
		name: 'Vitamin C Serum 30ml',
		description: 'Brightening vitamin C facial serum',
		price: 22.99,
		originalPrice: 34.99,
		category: 'personal-care',
		subcategory: 'skincare',
		stock: 68,
		image: '✨',
		rating: 4.8,
		reviews: 289,
		sku: 'PC-009',
		inStock: true,
		featured: true
	},

	// ========================================
	// MORE BEAUTY
	// ========================================
	{
		id: 96,
		name: 'Blush Powder Compact',
		description: 'Highly pigmented blush powder',
		price: 10.99,
		originalPrice: 16.99,
		category: 'beauty',
		subcategory: 'makeup',
		stock: 95,
		image: '💄',
		rating: 4.7,
		reviews: 212,
		sku: 'BEAUT-007',
		inStock: true,
		featured: false
	},
	{
		id: 97,
		name: 'Nail Polish Collection 6-Pack',
		description: 'Set of 6 trendy nail polish colors',
		price: 12.99,
		originalPrice: 19.99,
		category: 'beauty',
		subcategory: 'nails',
		stock: 108,
		image: '💅',
		rating: 4.6,
		reviews: 156,
		sku: 'BEAUT-008',
		inStock: true,
		featured: false
	},
	{
		id: 98,
		name: 'Face Mask Sheet Set 10',
		description: 'Pack of 10 hydrating face mask sheets',
		price: 14.99,
		originalPrice: 22.99,
		category: 'beauty',
		subcategory: 'skincare',
		stock: 142,
		image: '😷',
		rating: 4.5,
		reviews: 189,
		sku: 'BEAUT-009',
		inStock: true,
		featured: false
	},

	// ========================================
	// MORE CLOTHING
	// ========================================
	{
		id: 99,
		name: 'Socks Cotton Pack 12',
		description: 'Pack of 12 comfortable cotton socks',
		price: 16.99,
		originalPrice: 24.99,
		category: 'clothing',
		subcategory: 'accessories',
		stock: 200,
		image: '🧦',
		rating: 4.5,
		reviews: 267,
		sku: 'CLTH-006',
		inStock: true,
		featured: false
	},
	{
		id: 100,
		name: 'Baseball Cap Sports',
		description: 'Adjustable sports baseball cap',
		price: 14.99,
		originalPrice: 22.99,
		category: 'clothing',
		subcategory: 'accessories',
		stock: 87,
		image: '🧢',
		rating: 4.4,
		reviews: 145,
		sku: 'CLTH-007',
		inStock: true,
		featured: false
	},
	{
		id: 101,
		name: 'Underwear Premium Set',
		description: 'Set of 5 premium comfort underwear',
		price: 24.99,
		originalPrice: 39.99,
		category: 'clothing',
		subcategory: 'undergarments',
		stock: 95,
		image: '👕',
		rating: 4.6,
		reviews: 201,
		sku: 'CLTH-008',
		inStock: true,
		featured: false
	},
	{
		id: 102,
		name: 'Scarf Wool Cozy',
		description: 'Warm wool winter scarf',
		price: 19.99,
		originalPrice: 29.99,
		category: 'clothing',
		subcategory: 'accessories',
		stock: 52,
		image: '🧣',
		rating: 4.7,
		reviews: 178,
		sku: 'CLTH-009',
		inStock: true,
		featured: false
	},

	// ========================================
	// MORE BOOKS
	// ========================================
	{
		id: 103,
		name: 'Biography: Legendary Life',
		description: 'Inspiring biography of a legendary figure',
		price: 18.99,
		originalPrice: 28.99,
		category: 'books',
		subcategory: 'biography',
		stock: 48,
		image: '📖',
		rating: 4.7,
		reviews: 189,
		sku: 'BOOK-005',
		inStock: true,
		featured: false
	},
	{
		id: 104,
		name: 'Mystery Novel: The Secret',
		description: 'Thrilling mystery novel',
		price: 16.99,
		originalPrice: 24.99,
		category: 'books',
		subcategory: 'fiction',
		stock: 72,
		image: '📚',
		rating: 4.8,
		reviews: 234,
		sku: 'BOOK-006',
		inStock: true,
		featured: true
	},
	{
		id: 105,
		name: 'Cookbook: Healthy Recipes',
		description: '200+ healthy recipes cookbook',
		price: 22.99,
		originalPrice: 34.99,
		category: 'books',
		subcategory: 'reference',
		stock: 45,
		image: '🍳',
		rating: 4.6,
		reviews: 145,
		sku: 'BOOK-007',
		inStock: true,
		featured: false
	},

	// ========================================
	// SMART HOME & IoT DEVICES
	// ========================================
	{
		id: 106,
		name: 'Smart Doorbell with Camera',
		description: 'WiFi video doorbell with night vision',
		price: 89.99,
		originalPrice: 129.99,
		category: 'devices',
		subcategory: 'smart-home',
		stock: 38,
		image: '🔔',
		rating: 4.7,
		reviews: 312,
		sku: 'SMRT-001',
		inStock: true,
		featured: true
	},
	{
		id: 107,
		name: 'Smart Light Bulbs 4-Pack',
		description: 'WiFi RGB smart bulbs with app control',
		price: 49.99,
		originalPrice: 69.99,
		category: 'devices',
		subcategory: 'smart-home',
		stock: 125,
		image: '💡',
		rating: 4.5,
		reviews: 287,
		sku: 'SMRT-002',
		inStock: true,
		featured: false
	},
	{
		id: 108,
		name: 'Smart Thermostat Pro',
		description: 'Learning thermostat with remote control',
		price: 199.99,
		originalPrice: 299.99,
		category: 'devices',
		subcategory: 'smart-home',
		stock: 42,
		image: '🌡️',
		rating: 4.8,
		reviews: 445,
		sku: 'SMRT-003',
		inStock: true,
		featured: true
	},
	{
		id: 109,
		name: 'Smart Speaker Voice Assistant',
		description: 'Premium smart speaker with music control',
		price: 79.99,
		originalPrice: 119.99,
		category: 'devices',
		subcategory: 'smart-home',
		stock: 67,
		image: '🔊',
		rating: 4.6,
		reviews: 523,
		sku: 'SMRT-004',
		inStock: true,
		featured: false
	},
	{
		id: 110,
		name: 'Smart Door Lock',
		description: 'Keyless entry smart lock with app control',
		price: 159.99,
		originalPrice: 229.99,
		category: 'devices',
		subcategory: 'smart-home',
		stock: 31,
		image: '🔐',
		rating: 4.7,
		reviews: 389,
		sku: 'SMRT-005',
		inStock: true,
		featured: true
	},

	// ========================================
	// GAMING & PERIPHERALS
	// ========================================
	{
		id: 111,
		name: 'Gaming Monitor 165Hz 27-inch',
		description: 'Curved gaming monitor with 1ms response',
		price: 299.99,
		originalPrice: 449.99,
		category: 'electronics',
		subcategory: 'monitors',
		stock: 28,
		image: '🖥️',
		rating: 4.9,
		reviews: 567,
		sku: 'GAME-001',
		inStock: true,
		featured: true
	},
	{
		id: 112,
		name: 'Gaming Mouse Wireless',
		description: 'Professional gaming mouse with 8K polling',
		price: 59.99,
		originalPrice: 89.99,
		category: 'electronics',
		subcategory: 'gaming-peripherals',
		stock: 94,
		image: '🖱️',
		rating: 4.8,
		reviews: 623,
		sku: 'GAME-002',
		inStock: true,
		featured: false
	},
	{
		id: 113,
		name: 'Mechanical Keyboard Gaming RGB',
		description: '104-key gaming keyboard with Cherry switches',
		price: 129.99,
		originalPrice: 189.99,
		category: 'electronics',
		subcategory: 'gaming-peripherals',
		stock: 56,
		image: '⌨️',
		rating: 4.7,
		reviews: 478,
		sku: 'GAME-003',
		inStock: true,
		featured: false
	},
	{
		id: 114,
		name: 'Gaming Headset 7.1 Surround',
		description: 'Professional gaming headset with noise cancelling',
		price: 89.99,
		originalPrice: 129.99,
		category: 'electronics',
		subcategory: 'gaming-peripherals',
		stock: 72,
		image: '🎧',
		rating: 4.6,
		reviews: 334,
		sku: 'GAME-004',
		inStock: true,
		featured: false
	},
	{
		id: 115,
		name: 'Gaming Chair Ergonomic',
		description: 'High-back gaming chair with lumbar support',
		price: 249.99,
		originalPrice: 399.99,
		category: 'electronics',
		subcategory: 'furniture',
		stock: 19,
		image: '🪑',
		rating: 4.5,
		reviews: 289,
		sku: 'GAME-005',
		inStock: true,
		featured: false
	},

	// ========================================
	// AUDIO & MUSIC
	// ========================================
	{
		id: 116,
		name: 'Studio Monitor Speakers 5-inch',
		description: 'Professional studio monitors pair',
		price: 199.99,
		originalPrice: 299.99,
		category: 'electronics',
		subcategory: 'audio',
		stock: 35,
		image: '🔉',
		rating: 4.8,
		reviews: 267,
		sku: 'AUDIO-001',
		inStock: true,
		featured: false
	},
	{
		id: 117,
		name: 'Microphone Condenser Pro',
		description: 'Professional studio microphone with stand',
		price: 129.99,
		originalPrice: 199.99,
		category: 'electronics',
		subcategory: 'audio',
		stock: 47,
		image: '🎤',
		rating: 4.7,
		reviews: 312,
		sku: 'AUDIO-002',
		inStock: true,
		featured: false
	},
	{
		id: 118,
		name: 'Vinyl Record Player Turntable',
		description: 'Retro turntable with Bluetooth and USB',
		price: 159.99,
		originalPrice: 249.99,
		category: 'electronics',
		subcategory: 'audio',
		stock: 42,
		image: '🎵',
		rating: 4.6,
		reviews: 198,
		sku: 'AUDIO-003',
		inStock: true,
		featured: true
	},

	// ========================================
	// PREMIUM ELECTRONICS
	// ========================================
	{
		id: 119,
		name: 'Tablet Pro 12.9-inch',
		description: 'Premium tablet with M1 processor',
		price: 799.99,
		originalPrice: 999.99,
		category: 'devices',
		subcategory: 'tablets',
		stock: 24,
		image: '📱',
		rating: 4.8,
		reviews: 456,
		sku: 'PREM-001',
		inStock: true,
		featured: true
	},
	{
		id: 120,
		name: 'Drone 4K Photography',
		description: '4K camera drone with 30min flight time',
		price: 649.99,
		originalPrice: 899.99,
		category: 'electronics',
		subcategory: 'drones',
		stock: 18,
		image: '🚁',
		rating: 4.7,
		reviews: 389,
		sku: 'PREM-002',
		inStock: true,
		featured: true
	},

	// ========================================
	// FITNESS & WELLNESS
	// ========================================
	{
		id: 121,
		name: 'Yoga Mat Premium Non-Slip',
		description: 'Eco-friendly yoga mat 6mm thick',
		price: 39.99,
		originalPrice: 59.99,
		category: 'accessories',
		subcategory: 'fitness',
		stock: 83,
		image: '🧘',
		rating: 4.7,
		reviews: 245,
		sku: 'FITN-001',
		inStock: true,
		featured: false
	},
	{
		id: 122,
		name: 'Dumbbells Adjustable Set',
		description: 'Adjustable dumbbells 5-52 lbs',
		price: 299.99,
		originalPrice: 449.99,
		category: 'accessories',
		subcategory: 'fitness',
		stock: 27,
		image: '💪',
		rating: 4.8,
		reviews: 534,
		sku: 'FITN-002',
		inStock: true,
		featured: true
	},
	{
		id: 123,
		name: 'Resistance Bands Set 5-Pack',
		description: 'Loop resistance bands with carry bag',
		price: 24.99,
		originalPrice: 39.99,
		category: 'accessories',
		subcategory: 'fitness',
		stock: 156,
		image: '🏋️',
		rating: 4.6,
		reviews: 412,
		sku: 'FITN-003',
		inStock: true,
		featured: false
	},
	{
		id: 124,
		name: 'Foam Roller Recovery Tool',
		description: 'High-density foam roller 12 inch',
		price: 29.99,
		originalPrice: 44.99,
		category: 'accessories',
		subcategory: 'fitness',
		stock: 72,
		image: '🔄',
		rating: 4.5,
		reviews: 289,
		sku: 'FITN-004',
		inStock: true,
		featured: false
	},

	// ========================================
	// HOME DECOR
	// ========================================
	{
		id: 125,
		name: 'Wall Art Canvas Paintings Set',
		description: 'Modern canvas art 3-piece set',
		price: 79.99,
		originalPrice: 129.99,
		category: 'home',
		subcategory: 'decor',
		stock: 48,
		image: '🖼️',
		rating: 4.6,
		reviews: 178,
		sku: 'HOME-001',
		inStock: true,
		featured: false
	},
	{
		id: 126,
		name: 'LED String Lights Warm White',
		description: '100 LED warm white string lights',
		price: 19.99,
		originalPrice: 34.99,
		category: 'home',
		subcategory: 'decor',
		stock: 234,
		image: '✨',
		rating: 4.7,
		reviews: 567,
		sku: 'HOME-002',
		inStock: true,
		featured: false
	},
	{
		id: 127,
		name: 'Throw Pillow Set 2-Pack',
		description: 'Soft velvet throw pillows assorted colors',
		price: 34.99,
		originalPrice: 54.99,
		category: 'home',
		subcategory: 'decor',
		stock: 95,
		image: '🛋️',
		rating: 4.5,
		reviews: 234,
		sku: 'HOME-003',
		inStock: true,
		featured: false
	},
	{
		id: 128,
		name: 'Desk Organizer Set 5-Piece',
		description: 'Wooden desk organizer with compartments',
		price: 44.99,
		originalPrice: 69.99,
		category: 'home',
		subcategory: 'office',
		stock: 67,
		image: '📦',
		rating: 4.6,
		reviews: 289,
		sku: 'HOME-004',
		inStock: true,
		featured: false
	},

	// ========================================
	// SNACKS & BEVERAGES
	// ========================================
	{
		id: 129,
		name: 'Protein Bars Variety Pack',
		description: '24 protein bars assorted flavors',
		price: 34.99,
		originalPrice: 49.99,
		category: 'foodstuffs',
		subcategory: 'snacks',
		stock: 142,
		image: '🍫',
		rating: 4.5,
		reviews: 312,
		sku: 'FOOD-001',
		inStock: true,
		featured: false
	},
	{
		id: 130,
		name: 'Dark Chocolate Premium 72%',
		description: 'Belgian dark chocolate 200g bar',
		price: 8.99,
		originalPrice: 12.99,
		category: 'foodstuffs',
		subcategory: 'snacks',
		stock: 267,
		image: '🍫',
		rating: 4.7,
		reviews: 434,
		sku: 'FOOD-002',
		inStock: true,
		featured: false
	},
	{
		id: 131,
		name: 'Energy Drink 12-Pack',
		description: 'Premium energy drink 12 cans',
		price: 24.99,
		originalPrice: 35.99,
		category: 'foodstuffs',
		subcategory: 'beverages',
		stock: 89,
		image: '🥤',
		rating: 4.4,
		reviews: 267,
		sku: 'FOOD-003',
		inStock: true,
		featured: false
	},
	{
		id: 132,
		name: 'Granola Muesli Organic 500g',
		description: 'Organic granola with dried fruits',
		price: 12.99,
		originalPrice: 18.99,
		category: 'foodstuffs',
		subcategory: 'breakfast',
		stock: 156,
		image: '🥣',
		rating: 4.6,
		reviews: 289,
		sku: 'FOOD-004',
		inStock: true,
		featured: false
	},

	// ========================================
	// CAMERA & PHOTOGRAPHY
	// ========================================
	{
		id: 133,
		name: 'Mirrorless Camera 24MP',
		description: 'Professional mirrorless camera with 4K video',
		price: 1299.99,
		originalPrice: 1799.99,
		category: 'electronics',
		subcategory: 'cameras',
		stock: 16,
		image: '📷',
		rating: 4.9,
		reviews: 678,
		sku: 'CAM-001',
		inStock: true,
		featured: true
	},
	{
		id: 134,
		name: 'Camera Lens 35mm F/1.8',
		description: 'Prime lens for portrait photography',
		price: 399.99,
		originalPrice: 599.99,
		category: 'electronics',
		subcategory: 'lenses',
		stock: 34,
		image: '🔍',
		rating: 4.8,
		reviews: 412,
		sku: 'CAM-002',
		inStock: true,
		featured: false
	},
	{
		id: 135,
		name: 'Tripod Professional Carbon Fiber',
		description: 'Lightweight carbon fiber tripod',
		price: 149.99,
		originalPrice: 229.99,
		category: 'accessories',
		subcategory: 'photography',
		stock: 58,
		image: '📸',
		rating: 4.7,
		reviews: 289,
		sku: 'CAM-003',
		inStock: true,
		featured: false
	},
	{
		id: 136,
		name: 'Ring Light 18-inch LED',
		description: 'Professional ring light for streaming',
		price: 79.99,
		originalPrice: 119.99,
		category: 'accessories',
		subcategory: 'photography',
		stock: 72,
		image: '💡',
		rating: 4.6,
		reviews: 334,
		sku: 'CAM-004',
		inStock: true,
		featured: false
	},
	{
		id: 137,
		name: 'Camera Bag Professional',
		description: 'Weather-resistant camera bag',
		price: 89.99,
		originalPrice: 139.99,
		category: 'accessories',
		subcategory: 'photography',
		stock: 45,
		image: '👜',
		rating: 4.5,
		reviews: 267,
		sku: 'CAM-005',
		inStock: true,
		featured: false
	},

	// ========================================
	// OUTDOOR & CAMPING
	// ========================================
	{
		id: 138,
		name: 'Tent 4-Person Camping',
		description: 'Waterproof camping tent for 4 people',
		price: 129.99,
		originalPrice: 199.99,
		category: 'accessories',
		subcategory: 'camping',
		stock: 42,
		image: '⛺',
		rating: 4.7,
		reviews: 345,
		sku: 'CAMP-001',
		inStock: true,
		featured: false
	},
	{
		id: 139,
		name: 'Sleeping Bag Winter Rated',
		description: 'Temperature rated -10C sleeping bag',
		price: 79.99,
		originalPrice: 119.99,
		category: 'accessories',
		subcategory: 'camping',
		stock: 67,
		image: '😴',
		rating: 4.6,
		reviews: 289,
		sku: 'CAMP-002',
		inStock: true,
		featured: false
	},
	{
		id: 140,
		name: 'Backpack Hiking 60L',
		description: 'Large hiking backpack with rain cover',
		price: 99.99,
		originalPrice: 159.99,
		category: 'accessories',
		subcategory: 'camping',
		stock: 58,
		image: '🎒',
		rating: 4.7,
		reviews: 412,
		sku: 'CAMP-003',
		inStock: true,
		featured: false
	},
	{
		id: 141,
		name: 'Portable Water Filter Straw',
		description: 'Lightweight water filter for hiking',
		price: 29.99,
		originalPrice: 44.99,
		category: 'accessories',
		subcategory: 'camping',
		stock: 156,
		image: '💧',
		rating: 4.5,
		reviews: 234,
		sku: 'CAMP-004',
		inStock: true,
		featured: false
	},
	{
		id: 142,
		name: 'Headlamp LED Rechargeable',
		description: 'Bright LED headlamp for night activities',
		price: 34.99,
		originalPrice: 54.99,
		category: 'accessories',
		subcategory: 'camping',
		stock: 89,
		image: '🔦',
		rating: 4.6,
		reviews: 267,
		sku: 'CAMP-005',
		inStock: true,
		featured: false
	},

	// ========================================
	// KITCHEN APPLIANCES
	// ========================================
	{
		id: 143,
		name: 'Air Fryer 6-Quart Capacity',
		description: 'Digital air fryer with 8 presets',
		price: 89.99,
		originalPrice: 139.99,
		category: 'home',
		subcategory: 'kitchen-appliances',
		stock: 45,
		image: '🍟',
		rating: 4.7,
		reviews: 523,
		sku: 'KITCH-001',
		inStock: true,
		featured: true
	},
	{
		id: 144,
		name: 'Instant Pot 8-Quart',
		description: 'Electric pressure cooker multi-function',
		price: 149.99,
		originalPrice: 229.99,
		category: 'home',
		subcategory: 'kitchen-appliances',
		stock: 38,
		image: '🥘',
		rating: 4.8,
		reviews: 678,
		sku: 'KITCH-002',
		inStock: true,
		featured: true
	},
	{
		id: 145,
		name: 'Toaster Oven Digital Convection',
		description: 'Convection toaster oven',
		price: 129.99,
		originalPrice: 199.99,
		category: 'home',
		subcategory: 'kitchen-appliances',
		stock: 32,
		image: '🍞',
		rating: 4.6,
		reviews: 389,
		sku: 'KITCH-003',
		inStock: true,
		featured: false
	},
	{
		id: 146,
		name: 'Smoothie Blender 1500W',
		description: 'High-power blender for smoothies',
		price: 119.99,
		originalPrice: 179.99,
		category: 'home',
		subcategory: 'kitchen-appliances',
		stock: 48,
		image: '🥤',
		rating: 4.7,
		reviews: 434,
		sku: 'KITCH-004',
		inStock: true,
		featured: false
	},
	{
		id: 147,
		name: 'Rice Cooker 10-Cup',
		description: 'Non-stick rice cooker',
		price: 59.99,
		originalPrice: 89.99,
		category: 'home',
		subcategory: 'kitchen-appliances',
		stock: 73,
		image: '🍚',
		rating: 4.5,
		reviews: 267,
		sku: 'KITCH-005',
		inStock: true,
		featured: false
	},

	// ========================================
	// OFFICE SUPPLIES & STATIONERY
	// ========================================
	{
		id: 148,
		name: 'Desk Chair Office Ergonomic',
		description: 'Ergonomic office chair with lumbar support',
		price: 299.99,
		originalPrice: 449.99,
		category: 'home',
		subcategory: 'office',
		stock: 28,
		image: '🪑',
		rating: 4.7,
		reviews: 445,
		sku: 'OFFIC-001',
		inStock: true,
		featured: false
	},
	{
		id: 149,
		name: 'Notebook Set 3-Pack Premium',
		description: 'Premium quality notebooks',
		price: 19.99,
		originalPrice: 34.99,
		category: 'accessories',
		subcategory: 'stationery',
		stock: 234,
		image: '📔',
		rating: 4.5,
		reviews: 178,
		sku: 'OFFIC-002',
		inStock: true,
		featured: false
	},
	{
		id: 150,
		name: 'Pen Set 12-Color Premium',
		description: 'Professional quality pen set',
		price: 24.99,
		originalPrice: 39.99,
		category: 'accessories',
		subcategory: 'stationery',
		stock: 189,
		image: '✏️',
		rating: 4.6,
		reviews: 212,
		sku: 'OFFIC-003',
		inStock: true,
		featured: false
	},
	{
		id: 151,
		name: 'Desk Organizer Desktop',
		description: 'Multi-compartment desk organizer',
		price: 34.99,
		originalPrice: 54.99,
		category: 'home',
		subcategory: 'office',
		stock: 95,
		image: '📦',
		rating: 4.5,
		reviews: 189,
		sku: 'OFFIC-004',
		inStock: true,
		featured: false
	},
	{
		id: 152,
		name: 'Sticky Notes Bundle 100',
		description: 'Assorted color sticky notes',
		price: 9.99,
		originalPrice: 14.99,
		category: 'accessories',
		subcategory: 'stationery',
		stock: 567,
		image: '📝',
		rating: 4.4,
		reviews: 145,
		sku: 'OFFIC-005',
		inStock: true,
		featured: false
	},

	// ========================================
	// PET SUPPLIES
	// ========================================
	{
		id: 153,
		name: 'Dog Bed Orthopedic Memory Foam',
		description: 'Comfortable orthopedic dog bed',
		price: 79.99,
		originalPrice: 119.99,
		category: 'accessories',
		subcategory: 'pet-supplies',
		stock: 43,
		image: '🐕',
		rating: 4.7,
		reviews: 345,
		sku: 'PET-001',
		inStock: true,
		featured: false
	},
	{
		id: 154,
		name: 'Cat Tree Multi-Level',
		description: 'Multi-level cat tree with scratchers',
		price: 99.99,
		originalPrice: 159.99,
		category: 'accessories',
		subcategory: 'pet-supplies',
		stock: 38,
		image: '🐱',
		rating: 4.6,
		reviews: 289,
		sku: 'PET-002',
		inStock: true,
		featured: false
	},
	{
		id: 155,
		name: 'Pet Food Bowl Set Stainless',
		description: 'Stainless steel pet food bowls',
		price: 24.99,
		originalPrice: 39.99,
		category: 'accessories',
		subcategory: 'pet-supplies',
		stock: 156,
		image: '🥣',
		rating: 4.5,
		reviews: 212,
		sku: 'PET-003',
		inStock: true,
		featured: false
	},
	{
		id: 156,
		name: 'Dog Collar GPS Tracker',
		description: 'GPS tracker collar for dogs',
		price: 79.99,
		originalPrice: 119.99,
		category: 'accessories',
		subcategory: 'pet-supplies',
		stock: 51,
		image: '📍',
		rating: 4.6,
		reviews: 267,
		sku: 'PET-004',
		inStock: true,
		featured: true
	},
	{
		id: 157,
		name: 'Pet Grooming Kit 10-Piece',
		description: 'Complete pet grooming tools',
		price: 44.99,
		originalPrice: 69.99,
		category: 'accessories',
		subcategory: 'pet-supplies',
		stock: 67,
		image: '✂️',
		rating: 4.5,
		reviews: 189,
		sku: 'PET-005',
		inStock: true,
		featured: false
	},

	// ========================================
	// SPORTS & OUTDOOR GEAR
	// ========================================
	{
		id: 158,
		name: 'Mountain Bike 21-Speed',
		description: 'All-terrain mountain bike',
		price: 349.99,
		originalPrice: 549.99,
		category: 'accessories',
		subcategory: 'sports',
		stock: 24,
		image: '🚴',
		rating: 4.7,
		reviews: 389,
		sku: 'SPORT-001',
		inStock: true,
		featured: true
	},
	{
		id: 159,
		name: 'Skateboard Pro Deck',
		description: 'Professional skateboard deck',
		price: 79.99,
		originalPrice: 119.99,
		category: 'accessories',
		subcategory: 'sports',
		stock: 56,
		image: '🛹',
		rating: 4.6,
		reviews: 267,
		sku: 'SPORT-002',
		inStock: true,
		featured: false
	},
	{
		id: 160,
		name: 'Roller Skates Quad',
		description: 'Comfortable quad roller skates',
		price: 89.99,
		originalPrice: 139.99,
		category: 'accessories',
		subcategory: 'sports',
		stock: 42,
		image: '⛸️',
		rating: 4.5,
		reviews: 178,
		sku: 'SPORT-003',
		inStock: true,
		featured: false
	},
	{
		id: 161,
		name: 'Basketball Official Size',
		description: 'Official size basketball',
		price: 34.99,
		originalPrice: 54.99,
		category: 'accessories',
		subcategory: 'sports',
		stock: 89,
		image: '🏀',
		rating: 4.4,
		reviews: 145,
		sku: 'SPORT-004',
		inStock: true,
		featured: false
	},
	{
		id: 162,
		name: 'Tennis Racket Carbon',
		description: 'Carbon fiber tennis racket',
		price: 129.99,
		originalPrice: 199.99,
		category: 'accessories',
		subcategory: 'sports',
		stock: 38,
		image: '🎾',
		rating: 4.6,
		reviews: 234,
		sku: 'SPORT-005',
		inStock: true,
		featured: false
	},

	// ========================================
	// BEVERAGES & SUPPLEMENTS
	// ========================================
	{
		id: 163,
		name: 'Vitamin Supplement Multi 90-Count',
		description: 'Daily multivitamin supplement',
		price: 19.99,
		originalPrice: 29.99,
		category: 'foodstuffs',
		subcategory: 'supplements',
		stock: 234,
		image: '💊',
		rating: 4.5,
		reviews: 267,
		sku: 'SUPP-001',
		inStock: true,
		featured: false
	},
	{
		id: 164,
		name: 'Protein Powder Whey 2lb',
		description: 'Whey protein powder 2lb bag',
		price: 34.99,
		originalPrice: 54.99,
		category: 'foodstuffs',
		subcategory: 'supplements',
		stock: 178,
		image: '🏋️',
		rating: 4.6,
		reviews: 345,
		sku: 'SUPP-002',
		inStock: true,
		featured: false
	},
	{
		id: 165,
		name: 'Creatine Monohydrate Powder',
		description: 'Pure creatine monohydrate powder',
		price: 24.99,
		originalPrice: 39.99,
		category: 'foodstuffs',
		subcategory: 'supplements',
		stock: 145,
		image: '⚡',
		rating: 4.5,
		reviews: 212,
		sku: 'SUPP-003',
		inStock: true,
		featured: false
	},
	{
		id: 166,
		name: 'Omega-3 Fish Oil 120 Capsules',
		description: 'Premium fish oil supplement',
		price: 29.99,
		originalPrice: 44.99,
		category: 'foodstuffs',
		subcategory: 'supplements',
		stock: 198,
		image: '🐟',
		rating: 4.6,
		reviews: 289,
		sku: 'SUPP-004',
		inStock: true,
		featured: false
	},
	{
		id: 167,
		name: 'Electrolyte Drink Mix 30-Pack',
		description: 'Electrolyte sports drink mix',
		price: 19.99,
		originalPrice: 34.99,
		category: 'foodstuffs',
		subcategory: 'beverages',
		stock: 267,
		image: '💧',
		rating: 4.4,
		reviews: 178,
		sku: 'SUPP-005',
		inStock: true,
		featured: false
	},

	// ========================================
	// TOYS & GAMES
	// ========================================
	{
		id: 168,
		name: 'Board Game Strategy Premium',
		description: 'Popular strategy board game',
		price: 44.99,
		originalPrice: 69.99,
		category: 'accessories',
		subcategory: 'games',
		stock: 67,
		image: '🎲',
		rating: 4.6,
		reviews: 234,
		sku: 'GAME-006',
		inStock: true,
		featured: false
	},
	{
		id: 169,
		name: 'Puzzle 1000-Piece',
		description: '1000 piece premium puzzle',
		price: 24.99,
		originalPrice: 39.99,
		category: 'accessories',
		subcategory: 'games',
		stock: 145,
		image: '🧩',
		rating: 4.5,
		reviews: 189,
		sku: 'GAME-007',
		inStock: true,
		featured: false
	},
	{
		id: 170,
		name: 'Action Figure Collectible',
		description: 'Limited edition action figure',
		price: 34.99,
		originalPrice: 54.99,
		category: 'accessories',
		subcategory: 'toys',
		stock: 89,
		image: '🦸',
		rating: 4.7,
		reviews: 267,
		sku: 'TOY-001',
		inStock: true,
		featured: false
	},
	{
		id: 171,
		name: 'LEGO Building Set Advanced',
		description: 'Advanced LEGO building set',
		price: 79.99,
		originalPrice: 119.99,
		category: 'accessories',
		subcategory: 'toys',
		stock: 54,
		image: '🧱',
		rating: 4.8,
		reviews: 445,
		sku: 'TOY-002',
		inStock: true,
		featured: true
	},
	{
		id: 172,
		name: 'Drone Mini Beginner',
		description: 'Small beginner-friendly drone',
		price: 59.99,
		originalPrice: 89.99,
		category: 'accessories',
		subcategory: 'toys',
		stock: 76,
		image: '🚁',
		rating: 4.5,
		reviews: 234,
		sku: 'TOY-003',
		inStock: true,
		featured: false
	},

	// ========================================
	// AUTOMOTIVE ACCESSORIES
	// ========================================
	{
		id: 173,
		name: 'Car Phone Mount Dashboard',
		description: 'Adjustable car phone mount',
		price: 19.99,
		originalPrice: 34.99,
		category: 'accessories',
		subcategory: 'automotive',
		stock: 234,
		image: '📱',
		rating: 4.6,
		reviews: 389,
		sku: 'AUTO-001',
		inStock: true,
		featured: false
	},
	{
		id: 174,
		name: 'Car Charger Dual USB Fast',
		description: 'Dual USB fast charging car charger',
		price: 24.99,
		originalPrice: 39.99,
		category: 'accessories',
		subcategory: 'automotive',
		stock: 189,
		image: '🔌',
		rating: 4.5,
		reviews: 267,
		sku: 'AUTO-002',
		inStock: true,
		featured: false
	},
	{
		id: 175,
		name: 'Car Air Purifier HEPA',
		description: 'HEPA filter car air purifier',
		price: 49.99,
		originalPrice: 79.99,
		category: 'accessories',
		subcategory: 'automotive',
		stock: 78,
		image: '💨',
		rating: 4.5,
		reviews: 178,
		sku: 'AUTO-003',
		inStock: true,
		featured: false
	},
	{
		id: 176,
		name: 'Dash Cam 1080P Full HD',
		description: '1080P Full HD dash camera',
		price: 79.99,
		originalPrice: 129.99,
		category: 'electronics',
		subcategory: 'automotive',
		stock: 56,
		image: '📹',
		rating: 4.6,
		reviews: 345,
		sku: 'AUTO-004',
		inStock: true,
		featured: true
	},
	{
		id: 177,
		name: 'Car Seat Covers Premium',
		description: 'Protective car seat covers',
		price: 69.99,
		originalPrice: 109.99,
		category: 'accessories',
		subcategory: 'automotive',
		stock: 67,
		image: '🪑',
		rating: 4.5,
		reviews: 212,
		sku: 'AUTO-005',
		inStock: true,
		featured: false
	}
];

module.exports = {
	productSchema,
	mockProducts
};
